#!/bin/bash

#shopt -s extglob


###################################################################
# Script to use different linguistic tools
#   - - dependency parser (DepPattern)
#   - - PoS tagger + NER + NEC (CitiusTools)
#   - - Sentiment Analysis (CitiusSentiment)
#
# Pablo Gamallo
# ProLNat@GE Group, CiTIUS
# University of Santiago de Compostela
###################################################################

############################
# Config
############################

MAIN_DIR="./Linguakit"
PROGS=$MAIN_DIR"/scripts"
DIRPARSER=$MAIN_DIR"/parsers"



############################
# Functions
############################

help()
{
  echo "Syntax: linguakit <lang> <module> <input> [options]
      
      language = gl, es, en, pt
      module = dep, tagger, mwe, recog, sent, tok
      input = path of the input (by default a txt file or gz/zip) 

      'dep'     dependency syntactic analysis
      'tagger'  part-of-speech tagging
      'mwe'     multiword extraction
      'recog'   language recognition
      'sent'    sentiment analysis
      'tok'     tokenizer

      Available command-line options:

      -a       'dep' option: simple dependency analysis (by default syntactic output)
      -fa      'dep' option: full dependency analysis
      -c       'dep' option: tagged text with syntactic information (for correction rules)
      -conll   'dep' option: CoNLL output style

      -noner   'tagger' option: no NER or NEC is processed (by default PoS tagger output)
      -ner     'tagger' option: PoS tagger with Named Entity Recognition - NER (only with 'tagger' module)
      -nec     'tagger' option: PoS tagger with Named Entity Classification - NEC (only with 'tagger' module)

      -chi     'mwe' option: chi-square co-occurrence measure (by default)
      -log     'mwe' option: loglikelihood 
      -scp     'mwe' option: symmetrical conditional probability
      -mi      'mwe' option: mutual information 
      -cooc    'mwe' option: co-occurrence counting
     
      -split   'tok' option: tokenization with splitting

      -s       'sent' and 'recog' options: if <input> is a string and not a file 
"
  exit
}


# Parámetros obrigatorios
[ $# -lt 3 ] && help
LING=$1
MOD=$2
FILE=$3

if [ "$LING" == "none" ]  ; then
  LING_back="none"
  LING="en"
fi


# Parámetros opcionais
OPT=""
[ "$4" != "" ] && OPT=$4

NAMEPARSER="$DIRPARSER/parserDefault-$LING"
FILTER="$PROGS/AdapterFreeling-${LING}.perl"
CONLL="$PROGS/saidaCoNLL-fa.perl"

SENT=$MAIN_DIR"/tagger/"$LING"/sentences-"$LING"_exe.perl" 
TOK=$MAIN_DIR"/tagger/"$LING"/tokens-"$LING"_exe.perl" 
SPLIT=$MAIN_DIR"/tagger/"$LING"/splitter-"$LING"_exe.perl"
LEMMA=$MAIN_DIR"/tagger/"$LING"/lemma-"$LING"_exe.perl"
NER=$MAIN_DIR"/tagger/"$LING"/ner-"$LING"_exe.perl"
TAGGER=$MAIN_DIR"/tagger/"$LING"/tagger-"$LING"_exe.perl" 
NEC=$MAIN_DIR"/tagger/"$LING"/nec-"$LING"_exe.perl"

SENTIMENT=$MAIN_DIR"/sentiment/nbayes.perl"
SENT_TRAIN=$MAIN_DIR"/sentiment/"$LING"/train_"$LING 
SENT_LEX=$MAIN_DIR"/sentiment/"$LING"/lex_"$LING

MWE=$MAIN_DIR"/mwe/mwe.perl"
MWE_FILT=$MAIN_DIR"/mwe/filtro_galextra.perl"
MWE_SIX=$MAIN_DIR"/mwe/six_tokens.perl"

QUELINGUA=$MAIN_DIR"/lanrecog/lanrecog.perl"
QUELINGUA_LEX=$MAIN_DIR"/lanrecog/lexicons"
QUELINGUA_SUFFIX=$MAIN_DIR"/lanrecog/morpho/suffix.txt"
###building a temporal lexicon:
for i in $QUELINGUA_LEX/* ; do cat $i |awk -v LANG=`basename $i |sed "s/\.lx//"` '{print $0"\t"LANG}' >> __tmp; done
QUELINGUA_LEX=__tmp 

if [ "$MOD" != "dep" ] &&  [ "$MOD" != "tagger" ] && [ "$MOD" != "sent" ] && [ "$MOD" != "mwe" ] && [ "$MOD" != "recog" ] && [ "$MOD" != "tok" ] ; then
  help;
  echo "help" ;
fi


if [ "$OPT" != "-a" ] &&  [ "$OPT" != "-fa" ] && [ "$OPT" != "-c" ] && [ "$OPT" != "-conll" ] &&  [ "$OPT" != "-nec" ] && [ "$OPT" != "-ner" ] && [ "$OPT" != "-noner" ] && [ "$OPT" != "-s" ]  && [ "$OPT" != "-chi" ]  && [ "$OPT" != "-log" ]  && [ "$OPT" != "-mi" ]  && [ "$OPT" != "-cooc" ]  && [ "$OPT" != "-scp" ] && [ "$OPT" != "-split" ]   && [ "$OPT" != "" ] ; then
#if  [ "$OPT" != "-a" ] ; then
  help;
  echo "help" ;
fi


case $LING in
  es) ;;
  en) ;;
  gl) ;;
  pt) ;;
  none) ;;
 # fr) ;;
  *) help
esac


#NAMEFILE=`basename $FILE`;

ZIP=`echo $FILE |awk '($0 ~ /(gz$|zip$)/) {print "zip"}'`


if [ "$MOD" != "recog" ] && [ "$LING_back" == "none" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  LING=`zcat $FILE |tr -d '\015' | $SENT  | $TOK   | $QUELINGUA $QUELINGUA_LEX $QUELINGUA_SUFFIX`
 else 
  LING=`cat  $FILE |tr -d '\015' | $SENT  | $TOK  | $QUELINGUA $QUELINGUA_LEX $QUELINGUA_SUFFIX`
 fi
 echo "language = $LING"
 NAMEPARSER="$DIRPARSER/parserDefault-$LING"
 FILTER="$PROGS/AdapterFreeling-${LING}.perl"
 CONLL="$PROGS/saidaCoNLL-fa.perl"

 SENT=$MAIN_DIR"/tagger/"$LING"/sentences-"$LING"_exe.perl" 
 TOK=$MAIN_DIR"/tagger/"$LING"/tokens-"$LING"_exe.perl" 
 SPLIT=$MAIN_DIR"/tagger/"$LING"/splitter-"$LING"_exe.perl"
 LEMMA=$MAIN_DIR"/tagger/"$LING"/lemma-"$LING"_exe.perl"
 NER=$MAIN_DIR"/tagger/"$LING"/ner-"$LING"_exe.perl"
 TAGGER=$MAIN_DIR"/tagger/"$LING"/tagger-"$LING"_exe.perl" 
 NEC=$MAIN_DIR"/tagger/"$LING"/nec-"$LING"_exe.perl"

 SENTIMENT=$MAIN_DIR"/sentiment/nbayes.perl"
 SENT_TRAIN=$MAIN_DIR"/sentiment/"$LING"/train_"$LING 
 SENT_LEX=$MAIN_DIR"/sentiment/"$LING"/lex_"$LING
fi

##by default dependency output
if [ "$MOD" == "dep" ] && [ "$OPT" == "" ]   ; then 
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER |
      $FILTER | $NAMEPARSER.perl "-a"  ;
 
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER |
       $FILTER | $NAMEPARSER.perl "-a"  ;
 fi

##Conll dependency output
elif [ "$MOD" == "dep" ] && [ "$OPT" == "-conll" ] ; then 
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER |
      $FILTER | $NAMEPARSER.perl "-fa" | $CONLL  ;
 
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER |
       $FILTER | $NAMEPARSER.perl  "-fa" | $CONLL  ;
 fi

##Other dependency outputs
elif [ "$MOD" == "dep" ] && [ "$OPT" != "" ] ; then 
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER |
      $FILTER | $NAMEPARSER.perl $OPT   ;
 
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER |
       $FILTER | $NAMEPARSER.perl  $OPT  ;
 fi

 ##by default PoS tagging
elif [ "$MOD" == "tagger" ] && [ "$OPT" == "" ] || [ "$OPT" == "-noner" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $LEMMA | $TAGGER 
 
 else 
   cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $LEMMA | $TAGGER
 fi

##PoS tagging with ner
elif [ "$MOD" == "tagger" ] && [ "$OPT" == "-ner" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER 
 
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER
 fi

##PoS tagging with ner
elif [ "$MOD" == "tagger" ] && [ "$OPT" == "-nec" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $NEC
 
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $NEC
 fi


##multiword extraction
##sentiment analysis
elif [ "$MOD" == "mwe" ] && [ "$OPT" == "" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $MWE_FILT | $MWE_SIX  | $MWE "-chi" 1
  
 else
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $MWE_FILT | $MWE_SIX  |$MWE  "-chi" 1
 fi

elif [ "$MOD" == "mwe" ] && [ "$OPT" != "" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $MWE_FILT | $MWE_SIX  | $MWE $OPT 1
  
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $MWE_FILT | $MWE_SIX  |$MWE  $OPT 1
 fi

##sentiment analysis
elif [ "$MOD" == "sent" ] && [ "$OPT" == "" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $SENTIMENT $SENT_TRAIN $SENT_LEX
  
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $SENTIMENT $SENT_TRAIN $SENT_LEX
 fi

##sentiment analysis with a string as input
elif [ "$MOD" == "sent" ] && [ "$OPT" == "-s" ] ; then
  echo  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT | $NER | $TAGGER | $SENTIMENT $SENT_TRAIN $SENT_LEX

##language recognition
elif [ "$MOD" == "recog" ] && [ "$OPT" == "" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK  | $QUELINGUA $QUELINGUA_LEX $QUELINGUA_SUFFIX
  
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK  | $QUELINGUA $QUELINGUA_LEX $QUELINGUA_SUFFIX
 fi

##tokenizer
##tokenizer
elif [ "$MOD" == "tok" ] && [ "$OPT" == "" ] ; then
 if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK 
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK 
 fi
##tokenizer with splitting
elif [ "$MOD" == "tok" ] && [ "$OPT" == "-split" ] ; then
  if [ "$ZIP" == "zip" ] ; then
  zcat $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT
 else 
  cat  $FILE |tr -d '\015' | $SENT  | $TOK | $SPLIT
 fi


##language recognition with a string as input
elif [ "$MOD" == "recog" ] && [ "$OPT" == "-s" ] ; then
  echo $FILE |tr -d '\015' | $SENT  | $TOK  | $QUELINGUA $QUELINGUA_LEX $QUELINGUA_SUFFIX
fi


rm __tmp
